# -*- coding: utf-8 -*-
"""Youtube-Webscraper.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1R0LMCt2hDb1g9FCRbFp5Kmp39XlIrqb4
"""

import requests, urllib.request, time, re
from bs4 import BeautifulSoup

STATUS_OK = 200
MAX_IMAGES = 10
YOUTUBE_URL = "https://www.youtube.com/"
info_index = 0
vid_index = info_index + 1
invalid_images = 0


def downloadImage(url, title):
  title = title.replace("/", "") + ".jpg"
  urllib.request.urlretrieve(url, title)


response = requests.get(YOUTUBE_URL)

if response.status_code == STATUS_OK:
  
  data = BeautifulSoup(response.text, "html.parser")

  videos = data.findAll("div", {"class":"video-thumb"})
  infos = data.findAll("h3", {"class":"yt-lockup-title"})

  regex = re.compile(r'^https:\/\/.{1,}')

  while vid_index <= MAX_IMAGES:
    img_url = videos[vid_index].find("img")["src"]

    if re.match(regex, img_url) is not None:
      title = infos[info_index].find("a")["title"]
      print("Saving image thumbnail: " + title)
      downloadImage(img_url, title)      
      time.sleep(1)
    else:
      invalid_images += 1

    vid_index +=  1
    info_index += 1

  print(f'\nDONE. Saved {MAX_IMAGES - invalid_images} image(s). {invalid_images} image URLS invalid.')

